puddle/conversation/urls.py
from django.urls import path

from . import views

app_name = 'conversation'

urlpatterns = [
  path('', views.inbox, name='inbox'),
  path('<int:pk>/', views.detail, name='detail'),
  path('new/<int:item_pk>/', views.new_conversation, name="new")
]

puddle/core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
  path('', views.index, name='index'),
  path('contact/', views.contact, name='contact'),
  path('singup/', views.singup, name='singup'),
  path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
]

puddle/dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
]

puddle/item/urls.py
from django.urls import path

from . import views

app_name = 'item'

urlpatterns = [
  path('', views.items, name='items'),
  path('new/', views.new, name='new'),
  path('<int:pk>/', views.detail, name='detail'),
  path('<int:pk>/delete/', views.delete, name='delete'),
  path('<int:pk>/edit/', views.edit, name='edit'),
]

puddle/puddle/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin

from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('inbox/', include('conversation.urls')),
    # path('contact/', contact, name='contact'),
    path('admin/', admin.site.urls)

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

puddle/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class LoginForm(AuthenticationForm):
  username = forms.CharField(widget=forms.TextInput(
    attrs={
      'placeholder': 'Your username',
      'class': 'w-full py-4 px-6 rounded-xl'
    }
  ))
  password = forms.CharField(widget=forms.PasswordInput(
    attrs={
      'placeholder': 'Your password',
      'class': 'w-full py-4 px-6 rounded-xl'
    }
  ))

class SingUpForm(UserCreationForm):
  class Meta:
    model = User
    fields =('username', 'email', 'password1', 'password2')

  username = forms.CharField(widget=forms.TextInput(attrs={
    'placeholder': 'Your username',
    'class': 'w-full py-4 px-6 rounded-xl'
  }))
  email = forms.CharField(widget=forms.EmailInput(attrs={
    'placeholder': 'Your email',
    'class': 'w-full py-4 px-6 rounded-xl'
  }))
  password1 = forms.CharField(widget=forms.PasswordInput(attrs={
    'placeholder': 'Your password',
    'class': 'w-full py-4 px-6 rounded-xl'
  }))
  password2 = forms.CharField(widget=forms.PasswordInput(attrs={
    'placeholder': 'Repeat your password',
    'class': 'w-full py-4 px-6 rounded-xl'
  })) 

puddle/core/views.py
from django.shortcuts import redirect, render

from item.models import Category, Item

from .forms import SingUpForm

def index(request):
  items = Item.objects.filter(is_sold=False)[0:6]
  categories = Category.objects.all()
  return render(request, 'core/index.html', {
    'categories': categories,
    'items': items
  })

def contact(request):
  return render(request, 'core/contact.html')

# todo: create singup view
def singup(request):
  if request.method == 'POST':
    form = SingUpForm(request.POST)

    if form.is_valid():
      form.save()
      return redirect('/login/')
  else:
    form = SingUpForm()
  
  return render(request, 'core/singup.html', {
    'form': form
  })

puddle/core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}{% endblock %} | Puddle</title>
  <script src="https://cdn.tailwindcss.com"></script>

</head>
<body>
  <nav class="relative p-6 flex justify-between items-center border-b
  border-gray-200">
    <a href="/" class="text-xl font-semibold">Puddle</a>
    
    <ul class="space-x-6 flex">
      <li><a href="{% url 'item:new' %}" class="text-lg font-semibold hover:text-gray-500">New item</a></li>
      <li><a href="{% url 'item:items' %}" class="text-lg font-semibold hover:text-gray-500">Browse</a></li>

      {% if request.user.is_authenticated %}
        <li><a href="{% url 'conversation:inbox' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Inbox</a></li>
        <li><a href="{% url 'dashboard:index' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Dashbord</a></li>
      {% else %}
        <li><a href="{% url 'core:singup' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Sign up</a></li>
        <li><a href="{% url 'core:login' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Login in</a></li>
      {% endif %}
    </ul>
  </nav>
  <div class="p-6 bg-slate-100">
    {% block content %}
    {% endblock %}
  </div>
  <footer class="p-6 flex justify-between bg-gray-800">
    <div class="w-3/5 pr-10">
      <h3 class="mb-5 font-semibold text-gray-400">About</h3>
      <p class="text-lg text-gray-500">
        Lorem Ipsum is simply dummy text of the printing and 
        typesetting industry.
      </p>
    </div>
    <div class="w-1/3">
      <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>
      <ul
        class="space-y-2"
      >
       <li><a href="" class="text-lg text-teal-500 hover:text-teal-700">About</a></li> 
       <li><a href="{%url 'core:contact' %}" class="text-lg text-teal-500 hover:text-teal-700">Contact</a></li> 
       <li><a href="" class="text-lg text-teal-500 hover:text-teal-700">Privacy Police</a></li> 
       <li><a href="" class="text-lg text-teal-500 hover:text-teal-700">Term of use</a></li> 
      </ul>
    </div>
  </footer>
</body>
</html>

puddle/core/templates/core/contact.html
{% extends 'core/base.html' %}

{% block title %}Contact{% endblock %}

{% block content %}
<h1>The contact page</h1>
{% endblock %}

puddle/core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %}Welcome{% endblock %}

{% block content %}
  <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">Newest items</h2>
    
    <div class="grid grid-cols-3 gap-3"> 
      {% for item in items %}
        <div>
          <a href="{% url 'item:detail' item.id %}">
            <div>
              <img src="{{ item.image.url }}" alt="{{ item.name }}" class="rounded-t-xl">
            </div>

            <div class="p-6 bg-white rounded-b-xl">
              <h2 class="text-2xl">{{ item.name }}</h2>
              <p class="text-gray-500">Price: $ {{ item.price }}</p>
            </div>
          </a>
        </div>
      {% endfor %}
    </div>
  </div>
  <div class="mt-6 px-6 py-12 bg-gray-100 mt-2 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">Categories</h2>
      <div class="grid grid-cols-3 gap-3"> 
        {% for category in categories %}
          <div>
            <a href="#">
              <div class="p-6 bg-white rounded-xl">
                <h2 class="text-2xl">{{ category.name }}</h2>
                <p class="text-gray-500">{{ category.items.count }} items</p>
              </div>
            </a>
          </div>
        {% endfor %}
      </div>
  </div>
{% endblock %}

puddle/core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
 <div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
  <h1 class="my-6 text-3xl">login</h1>
  <form method="POST" action=".">
    {% csrf_token %}
    
    <!-- {{ form.as_p }} -->
    <!-- {{ form.non_field_erros }} -->
    
    <div class="mb-3">
      <label for="" class="inline-block mb-2 text-slate-600">Username</label>
      {{ form.username }}
    </div>

    <div class="mb-3">
      <label for="" class="inline-block mb-2 text-slate-300">Password</label>
      {{ form.password }}
    </div>

    {% if form.erros or form.non_field_erros %}
      <div class="mb-2 p-6 bg-red-100 rounded-xl">
        {% for field in form %}
          {{ field.erros }}
        {% endfor %}

        {{ form.non_field_errors }}
      </div>
    {% endif %}
    
    <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700
    rounded-xl text-white">
      Submit
    </button>
  </form>
 </div>
{% endblock %}

puddle/core/templates/core/singup.html
{% extends 'core/base.html' %}

{% block title %}Sing up{% endblock %}

{% block content %}
 <div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
  <h1 class="my-6 text-3xl">Singup</h1>
  <form method="POST" action=".">
    {% csrf_token %}
    
    <!-- {{ form.as_p }} -->
    <!-- {{ form.non_field_erros }} -->
    
    <div class="mb-3">
      <label for="" class="inline-block mb-2 text-slate-600">Username</label>
      {{ form.username }}
    </div>
    <div class="mb-3">
      <label for="" class="inline-block mb-2 text-slate-300">Email</label>
      {{ form.email }}
    </div>
    <div class="mb-3">
      <label for="" class="inline-block mb-2 text-slate-300">Password</label>
      {{ form.password1 }}
    </div>
    <div class="mb-3">
      <label for="" class="inline-block mb-2 text-slate-300">Repeat password</label>
      {{ form.password2 }}
    </div>

    {% if form.erros or form.non_field_erros %}
      <div class="mb-2 p-6 bg-red-100 rounded-xl">
        {% for field in form %}
          {{ field.erros }}
        {% endfor %}

        {{ form.non_field_errors }}
      </div>
    {% endif %}
    
    <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700
    rounded-xl text-white">
      Submit
    </button>
  </form>
 </div>
{% endblock %}